### ISSUE TITLE
Sentry Logback with Spring Boot does not pickup configuration from Spring

### ISSUE THREAD

**Issue by rharrahuzurv** [getsentry/sentry-java#4521]
### Integration

sentry

### Java Version

24

### Version

8.15.0

### Steps to Reproduce

Use a Spring Boot 3.4.5 application with Sentry 8.15.0 and enable Sentry logging:
```yaml
sentry:
  dsn: mydsngoeshere
  send-default-pii: true
  environment: ${ENVIRONMENT_NAME}
  logs:
    enabled: true
  logging:
    minimum-level: info
    minimum-event-level: info
    minimum-breadcrumb-level: debug
    enabled: true
```

### Expected Result

Logs should appear in Sentry Logs.

### Actual Result

Logs do not appear in Sentry logs.

As of this line (https://github.com/getsentry/sentry-java/blob/main/sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryLogbackInitializer.java#L58), `SentryOptions$Logs` is correctly detecting from the Spring properties that logs are enabled:
<img width="285" alt="Image" src="https://github.com/user-attachments/assets/18e08dc9-6801-4fce-a7fb-bce8874f71d4" />

As of this line (https://github.com/getsentry/sentry-java/blob/8.15.0/sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java#L71), `SentryOptions$Logs` is not using the properties, which is to be expected because these are external configurations:
<img width="288" alt="Image" src="https://github.com/user-attachments/assets/1cd0f775-b44c-4f7c-afd5-4695ac4ebd22" />

Once it reaches and invokes the method on this line (https://github.com/getsentry/sentry-java/blob/8.15.0/sentry/src/main/java/io/sentry/Sentry.java#L291) in `Sentry.init`, it should pick up the external configuration from Spring but does not. It resolves values from environment variables / system properties / classpath but never receives either the DSN or that logs are enabled configured in the Spring properties, resulting in logs never being sent:
<img width="1099" alt="Image" src="https://github.com/user-attachments/assets/f01807c1-c80e-4be6-ab15-ea901e864e2d" />
<img width="982" alt="Image" src="https://github.com/user-attachments/assets/877b5279-80c6-4740-abbd-e3fa49ea17df" />
