### ISSUE TITLE
Pull artifacts from CI/zeus to publish

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#951]
Dependent on #950, follow up #952

We want to use getsentry/craft to publish. That means splitting CI from publishing.
Once we get the artifacts (see #950) we would publish them to GH Actions (or zeus.ci).

With that, we can add the `.craft.yaml` to this repo so craft pulls the artifacts in order to make a release.

i.e:

```
github:
  owner: getsentry
  repo: sentry-java
targets:
  - name: maven
  - name: jcenter
  - name: github
  - name: registry
    type: sdk
    config:
      canonical: "maven:io.sentry:sentry"
 ....
```
For example in [sentry-cocoa](https://github.com/getsentry/sentry-cocoa/blob/master/.craft.yml), [sentry-dotnet](https://github.com/getsentry/sentry-dotnet/blob/main/.craft.yml), [sentry-react-native](https://github.com/getsentry/sentry-react-native/blob/master/.craft.yml).
